create table tb_cidade (
	id_cidade bigint generated by default as identity,
	qtd_habitantes bigint,
	nome varchar(50),
	primary key (id_cidade)
);
    
insert into tb_cidade (nome, qtd_habitantes) values ('Goiânia', 2123456565);
insert into tb_cidade (nome, qtd_habitantes) values ('São Paulo', 5897986546541);
insert into tb_cidade (nome, qtd_habitantes) values ('Curitiba', 1523456);
insert into tb_cidade (nome, qtd_habitantes) values ('Rio de Janeiro', 12345644);
insert into tb_cidade (nome, qtd_habitantes) values ('Campo Grande', 487143524165);
insert into tb_cidade (nome, qtd_habitantes) values ('Rio Grande do Norte', 658789123);
insert into tb_cidade (nome, qtd_habitantes) values ('Santa Catarina', 68578123);
insert into tb_cidade (nome, qtd_habitantes) values ('Palmas', 5464654871232);
insert into tb_cidade (nome, qtd_habitantes) values ('Belo Horizonte', 5646874);
insert into tb_cidade (nome, qtd_habitantes) values ('Aparecida de Goiânia', 421523456);
insert into tb_cidade (nome, qtd_habitantes) values ('Rio Verde', 15234523136);